server:
  port: 8082
  context-path: /springboot

girl:
  name: B
  age: 18
  content: name-> ${name},age-> ${age}

spring:
  profiles:
    active: prod

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
